FROM wso2/wso2am:2.6.0-alpine

RUN apk update && apk add --no-cache curl nano wget bash

RUN mkdir -p /src/app
WORKDIR /src/app

COPY package.json /src/app/package.json
RUN npm install
COPY . /src/app

EXPOSE 3000
CMD [ "npm", "start" ]





